const test = [
  {
    data: {
      galleryId: 23,
      blockId: 0,
      levelId: 0,
      name: "International Gallery (East)",
      galleryName: "International Gallery (East)",
      blockName: "",
      levelName: "",
      defaultSeats: "790",
      unitPrice: "1500",
      isUnitPriceEditing: false,
      isAllocateViewing: false,
      isDeAllocateViewing: false,
      isReservedViewing: false,
      isReleasedViewing: false,
      allocated: 0,
      totalAllocated: 0,
      deAllocated: 0,
      totalReserved: 20,
      reserved: 20,
      released: 0,
      totalCapacity: 790,
      availableCapacity: 770,
      isTicketGenerated: false,
    },
    expanded: true,
    children: [
      {
        data: {
          galleryId: 23,
          blockId: 47,
          levelId: 0,
          name: "M",
          galleryName: "International Gallery (East)",
          blockName: "M",
          levelName: "",
          defaultSeats: "790",
          unitPrice: "1500",
          isUnitPriceEditing: false,
          isAllocateViewing: false,
          isDeAllocateViewing: false,
          isReservedViewing: false,
          isReleasedViewing: false,
          allocated: 0,
          totalAllocated: 0,
          deAllocated: 0,
          totalReserved: 20,
          reserved: 20,
          released: 0,
          totalCapacity: 790,
          availableCapacity: 770,
          isTicketGenerated: false,
        },
        expanded: true,
        children: [
          {
            data: {
              galleryId: 23,
              blockId: 47,
              levelId: 26,
              name: "Upper",
              galleryName: "International Gallery (East)",
              blockName: "M",
              levelName: "Upper",
              defaultSeats: "440",
              unitPrice: "1500",
              isUnitPriceEditing: false,
              isAllocateViewing: false,
              isDeAllocateViewing: false,
              isReservedViewing: false,
              isReleasedViewing: false,
              allocated: 0,
              totalAllocated: 0,
              deAllocated: 0,
              totalReserved: 20,
              reserved: 20,
              released: 0,
              totalCapacity: 440,
              availableCapacity: 420,
              isTicketGenerated: false,
            },
          },
          {
            data: {
              galleryId: 23,
              blockId: 47,
              levelId: 26,
              name: "Lower",
              galleryName: "International Gallery (East)",
              blockName: "M",
              levelName: "Lower",
              defaultSeats: "440",
              unitPrice: "1500",
              isUnitPriceEditing: false,
              isAllocateViewing: false,
              isDeAllocateViewing: false,
              isReservedViewing: false,
              isReleasedViewing: false,
              allocated: 0,
              totalAllocated: 0,
              deAllocated: 0,
              totalReserved: 20,
              reserved: 20,
              released: 0,
              totalCapacity: 440,
              availableCapacity: 420,
              isTicketGenerated: false,
            },
          },
        ],
      },
    ],
  },
];

const test2 = [
  {
    data: {
      galleryId: 23,
      blockId: 0,
      levelId: 0,
      name: "International Gallery (East)",
      galleryName: "International Gallery (East)",
      blockName: "",
      levelName: "",
      defaultSeats: "790",
      unitPrice: "1500",
      isUnitPriceEditing: false,
      isAllocateViewing: false,
      isDeAllocateViewing: false,
      isReservedViewing: false,
      isReleasedViewing: false,
      allocated: 0,
      totalAllocated: 0,
      deAllocated: 0,
      totalReserved: 20,
      reserved: 20,
      released: 0,
      totalCapacity: 790,
      availableCapacity: 770,
      isTicketGenerated: false,
    },
    expanded: true,
    children: [
      {
        data: {
          galleryId: 23,
          blockId: 47,
          levelId: 26,
          name: "Upper",
          galleryName: "International Gallery (East)",
          blockName: "M",
          levelName: "Upper",
          defaultSeats: "440",
          unitPrice: "1500",
          isUnitPriceEditing: false,
          isAllocateViewing: false,
          isDeAllocateViewing: false,
          isReservedViewing: false,
          isReleasedViewing: false,
          allocated: 0,
          totalAllocated: 0,
          deAllocated: 0,
          totalReserved: 20,
          reserved: 20,
          released: 0,
          totalCapacity: 440,
          availableCapacity: 420,
          isTicketGenerated: false,
        },
      },
      {
        data: {
          galleryId: 23,
          blockId: 47,
          levelId: 26,
          name: "Lower",
          galleryName: "International Gallery (East)",
          blockName: "M",
          levelName: "Lower",
          defaultSeats: "440",
          unitPrice: "1500",
          isUnitPriceEditing: false,
          isAllocateViewing: false,
          isDeAllocateViewing: false,
          isReservedViewing: false,
          isReleasedViewing: false,
          allocated: 0,
          totalAllocated: 0,
          deAllocated: 0,
          totalReserved: 20,
          reserved: 20,
          released: 0,
          totalCapacity: 440,
          availableCapacity: 420,
          isTicketGenerated: false,
        },
      },
    ],
  },
];
